name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetches all Git history (needed for tools like Jest coverage)

      - name: "Set up Node.js (LTS)"
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Matches the version in `engines.node` (from package.json)
          cache: "npm"        # Caches `node_modules` for faster runs

      - name: "Install dependencies"
        run: npm ci
        env:
          CI: true          # Ensures installs are optimized for CI environments

      # --- Linting (ESLint as Checkstyle equivalent) ---
      - name: "Run ESLint (Checkstyle equivalent)"
        run: npm run lint

      # --- JSDoc Validation (Optional) ---
      - name: "Check JSDoc coverage"
        run: |
          npm install -g jsdoc
          jsdoc -c jsdoc.json  # Fail CI if JSDoc is missing (add your own rules)
        continue-on-error: true  # Optional: Remove to enforce strict doc checks

      # --- Tests + Coverage (60% threshold) ---
      - name: "Run Jest tests with coverage"
        run: npm test -- --coverage --coverageThreshold='{"global":{"lines":60}}'
