name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Use LTS version

      - name: Install dependencies
        run: npm ci

      # --- Linting (ESLint as Checkstyle equivalent) ---
      - name: Run ESLint
        run: npm run lint

      # --- JSDoc Validation (Optional) ---
      - name: Check JSDoc coverage
        run: |
          npm install -g jsdoc
          jsdoc -c jsdoc.json  # Fail CI if JSDoc is missing (add your own rules)

      # --- Tests + Coverage (60% threshold) ---
      - name: Run tests with coverage
        run: npm test -- --coverage --coverageThreshold='{"global":{"lines":60}}'
